# Project-wide Gradle settings.

# Enable AndroidX (Required for Jetpack Compose, Room, Material 3)
android.useAndroidX=true

# Enables non-transitive R classes for faster builds
android.nonTransitiveRClass=true

# Kotlin & JVM Build options
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official